print("hello welcome to GitHub")
print("2nd hello welcome")
print("3rd welcome to git")
print("kiran")
print("k v Nishanth gowda")
print("6th line cretaed")
print("nishanth fork")
print("manjesh yag")
print("manjesh")